# Generated by Django 2.2.4 on 2021-05-30 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fav_book_app', '0002_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked_books', to='fav_book_app.User'),
        ),
    ]
